var navigation = CardService.newNavigation();

function onOpen(e){
  var mainCard =  CardService.newCardBuilder();
  var cardSection = CardService.newCardSection()

  cardSection.addWidget(
    CardService.newTextParagraph().setText(
      "Patch SVG files generated by Tinkercad for import into RDworks. \n\nSelect the files in your google drive to get started."
    )
  );
  mainCard.addSection(cardSection);
  return mainCard.build();
   
}

function onConvert(e) {
  var outputCard =  CardService.newCardBuilder();
  var completedSection = CardService.newCardSection();
  var failedSection = CardService.newCardSection();

  completedSection.setHeader("Successfully Converted Files");
  failedSection.setHeader("Failed Files")

  var fileIds = e.formInputs.selected_files;
  console.log(e)

  var now = new Date();
  var newFolderName = "SVG Convert " + (now.getMonth()+1) + "-" +now.getDate()+"_"+now.getHours() +":" + twoDigitMinute( now.getMinutes());
  var newFileFolder = DriveApp.createFolder(newFolderName); 
  var moveToFolder = DriveApp.getRootFolder();

  var firstFileParents = DriveApp.getFileById(fileIds[0]).getParents();
  if(firstFileParents.hasNext()){
    moveToFolder = firstFileParents.next();
  }
  newFileFolder.moveTo(moveToFolder)

  for(var i=0; i<fileIds.length; i++){
    try{
      var newFile = tinkerCadSVGtoRDWorksSVG(fileIds[i]);
      newFile.moveTo(newFileFolder);
      completedSection.addWidget(CardService.newTextParagraph().setText(newFile.getName()));
    }
    catch(z){
      console.warn(fileIds[i])
      console.warn(z);
      failedSection.addWidget(CardService.newTextParagraph().setText(newFile.getName()));
    }
  }   

  outputCard.addSection(completedSection);
  // outputCard.addSection(failedSection);
  return outputCard.build(); 
}  

function genMainCard(fileItems){
  var mainCard =  CardService.newCardBuilder();
  var cardSection = CardService.newCardSection()

  var convertAction = CardService.newAction().setFunctionName('onConvert');

  cardSection.addWidget(
    CardService.newTextParagraph().setText(
      "Patch SVG files generated by Tinkercad for import into RDworks. \n\nSelect the files in your google drive and convert. New files will be placed in a new folder in the current location named 'SVG Converter' followed by the current date."
    )
  );    

  // cardSection.addWidget(
  //   CardService.newSelectionInput()
  //     .setType(CardService.SelectionInputType.DROPDOWN)
  //     .setTitle("File destination: ")
  //     .setFieldName("file_destination")
  //     .addItem("Download", "download", true)
  //     .addItem("Drive Folder", "folder", false)
  //     .addItem("Both", "both", false)
  // );

  cardSection.addWidget(
        CardService.newTextButton()
          .setText("Convert Selected SVGs")
          .setOnClickAction(convertAction));

  mainCard.addSection(cardSection);

  if(fileItems != undefined && fileItems.length != 0){
    var fileSection = CardService.newCardSection().setHeader("Selected SVG Files");
    var fileCheckBox = CardService.newSelectionInput()
        .setType(CardService.SelectionInputType.CHECK_BOX)
        .setFieldName("selected_files");

    for(var i=0; i < fileItems.length;i++){
      fileCheckBox.addItem(fileItems[i].title, fileItems[i].id,true);
    }

    fileSection.addWidget(fileCheckBox);
    mainCard.addSection(fileSection);
  }

  return mainCard.build();
}


function onSelect(e) {
    var files = [];
    if(e.drive.selectedItems != undefined){
      var temp = e.drive.selectedItems;
      for(var i=0;i<temp.length;i++){
        if(temp[i].mimeType == MimeType.SVG){
          files.push(temp[i]);
        }
      }
    }
    if(e.drive.activeCursorItem.mimeType == MimeType.SVG){
      files.push(e.drive.activeCursorItem);
    };

    return genMainCard(files);
}

function twoDigitMinute(x){
  if(x<10){
    return '0'+x;
  }
  return x
}
