var navigation = CardService.newNavigation();

function onOpen(e){
  var mainCard =  CardService.newCardBuilder();
  var cardSection = CardService.newCardSection()

  cardSection.addWidget(
    CardService.newTextParagraph().setText(
      "Patch SVG files generated by Tinkercad for import into RDworks. \n\nSelect the files in your google drive to get started."
    )
  );
  mainCard.addSection(cardSection);
  return mainCard.build();
   
}

function onConvert(e) {
  var builder = CardService.newCardBuilder();

  var selectedItems = e.drive.selectedItems;
  console.log(e.formInput.file_destination)
    
  console.log(e.drive)

  for (var i=0; i< selectedItems.length; i++){
     var item = selectedItems[i];
      
      var cardSection = CardService.newCardSection()
              .setHeader(item['title']);

      cardSection.addWidget(
        CardService.newTextParagraph()
                .setText("This files id; " + item['id']));

      builder.addSection(cardSection);
  }
  return builder.build();
}

function genMainCard(fileItems){
  var mainCard =  CardService.newCardBuilder();
  var cardSection = CardService.newCardSection()

  var convertAction = CardService.newAction().setFunctionName('onConvert');

  cardSection.addWidget(
    CardService.newTextParagraph().setText(
      "Patch SVG files generated by Tinkercad for import into RDworks. \n\nSelect the files in your google drive, set your download location, and convert."
    )
  );    

  cardSection.addWidget(
    CardService.newSelectionInput()
      .setType(CardService.SelectionInputType.DROPDOWN)
      .setTitle("File destination: ")
      .setFieldName("file_destination")
      .addItem("Download", "download", true)
      .addItem("Drive Folder", "folder", false)
      .addItem("Both", "both", false)
  );

  cardSection.addWidget(
        CardService.newTextButton()
          .setText("Convert Selected SVGs")
          .setOnClickAction(convertAction));

  mainCard.addSection(cardSection);

  if(fileItems != undefined && fileItems.length != 0){
    var fileSection = CardService.newCardSection().setHeader("Selected SVG Files");
    var fileCheckBox = CardService.newSelectionInput()
        .setType(CardService.SelectionInputType.CHECK_BOX)
        .setFieldName("selected_files");

    for(var i=0; i < fileItems.length;i++){
      fileCheckBox.addItem(fileItems[i].title, fileItems[i].id,true);
    }

    fileSection.addWidget(fileCheckBox);
    mainCard.addSection(fileSection);
  }

  return mainCard.build();
}


function onSelect(e) {
    var files = [];
    if(e.drive.selectedItems != undefined){
      var temp = e.drive.selectedItems;
      for(var i=0;i<temp.length;i++){
        if(temp[i].mimeType == MimeType.SVG){
          files.push(temp[i]);
        }
      }
    }
    if(e.drive.activeCursorItem.mimeType == MimeType.SVG){
      files.push(e.drive.activeCursorItem);
    };

    return genMainCard(files);
}
